server:
  port: 9000
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: org.n52.edis.pegelonline
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties.spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: org.n52.edis.pegelonlinekafkaconsumer.model
      properties.spring.json.value.default.type: org.n52.edis.pegelonlinekafkaconsumer.model.PegelonlineKafkaMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
edis:
  kafka:
    consumer:
      topic: de.itzbund.pegelonline
      group: de.itzbund.edis
      id: consumer01
  mqtt:
    enabled: true
    server-uris:
      - ssl://localhost:8883
    client-id-prefix: edis.pegelonline.kafka-consumer
    client-id: consumer01
    base-topic: edis/pegelonline
    file-persistence-enabled: false
    file-persistence-directory: /var/temp
    initial-connect-retry-attempts: 60
    initial-connect-retry-delay: 60000 # in milliseconds
    initial-maxAttempts: 20
    initial-maxDelay: 100
    reconnect: true
    clean-session: false
    connection-timeout: 60
    keep-alive-interval: 60
    message-delivery-monitor: logging
    qos: 0
    basic-authentication: true
    username: rabbitmq
    password: rabbitmq
    tls:
      tls-enabled: false
      peer-verification-enabled: true
      ca-cert-file: "/path/to/caCertFile.pem"
      client-cert-file: "/path/to/clientCertFile.pem"
      key-file: "/path/to/clientKey.pem"
      password: "bunnies"
logging:
  level:
    ssl: debug
    org.n52.edis: debug
management:
  health.rabbit.enabled: false
  endpoints.web.exposure.include: "info,health,metrics"
  endpoint:
    health.show-components: always
